CREATE TABLE EMP_COPY AS SELECT * FROM EMP WHERE 1=2;
SELECT * FROM EMP_COPY;
INSERT INTO EMP_COPY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (5555,'장원영','MANAGER',7839,'2023/05/22',4000,0,10);
INSERT INTO EMP_COPY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (7777,'차은우','MANAGER',7839,'2023-05-22',4000,0,10);    
INSERT INTO EMP_COPY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (8888,'김민종','MANAGER',7839,TO_DATE('22/05/2023','DD/MM/YYYY'),4000,0,10);
INSERT INTO EMP_COPY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    VALUES (9999,'김민','ANALYST',5555,SYSDATE,3000,NULL,10);

SELECT * FROM EMP_COPY;

SELECT*FROM EMP_COPY;

SELECT A.EMPNO,A.ENAME, A.JOB, A.MGR, A.HIREDATE,A.SAL,A.COMM, A.DEPTNO 
    FROM EMP A, SALGRADE B     
    WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL AND B.GRADE=2;

INSERT INTO EMP_COPY (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT A.EMPNO,A.ENAME, A.JOB, A.MGR, A.HIREDATE,A.SAL,A.COMM, A.DEPTNO 
    FROM EMP A, SALGRADE B     
    WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL AND B.GRADE=2;
    
SELECT * FROM EMP_COPY;

--데이터 변경 UPDATE
CREATE TABLE DEPT_COPY
    AS SELECT*FROM DEPT;

SELECT*FROM DEPT_COPY;
UPDATE DEPT_COPY
    SET LOC = 'JEJU';

SELECT*FROM DEPT_COPY;

--취소
ROLLBACK;

SELECT*FROM DEPT_COPY;

--30번 부서 이름과 위치 변경
SELECT * FROM DEPT_COPY WHERE DEPTNO=30;
SELECT DNAME,LOC FROM DEPT_COPY WHERE DEPTNO=30; --SALES, CHICAGO
UPDATE DEPT_COPY 
    SET DNAME = 'DA',
        LOC = 'SEOUL'
    WHERE DEPTNO=30;
    
SELECT*FROM DEPT_COPY;

SELECT*FROM EMP_COPY WHERE EMPNO=9999;
UPDATE EMP_COPY
    SET COMM = 1000
    WHERE EMPNO = 9999;

SELECT*FROM EMP_COPY;
SELECT*FROM DEPT_COPY;
SELECT DNAME, LOC FROM DEPT WHERE DEPTNO=30;
--DA SEOUL => SALES CHICAGO 로 변경 ( 서브쿼리 사용 )
UPDATE DEPT_COPY
    SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO=30)
    WHERE DEPTNO=30;

SELECT*FROM DEPT_COPY;
SELECT DEPTNO FROM DEPT_COPY WHERE DNAME='RESEARCH';
--DALLAS => BUSAN 으로 변경
UPDATE DEPT_COPY
    SET LOC = 'BUSAN'
    WHERE DEPTNO=(SELECT DEPTNO FROM DEPT_COPY WHERE DNAME='RESEARCH');
SELECT*FROM DEPT_COPY;

--데이터 삭제 DELETE
SELECT * FROM EMP_COPY;
DROP TABLE EMP_COPY;
CREATE TABLE EMP_COPY
    AS SELECT * FROM EMP;
SELECT*FROM EMP_COPY;

--데이터 일부 삭제
SELECT * FROM EMP_COPY WHERE JOB='CLERK';
DELETE EMP_COPY WHERE JOB = 'CLERK';

SELECT * FROM EMP_COPY;

--서브쿼리를 이용하여 데이터 일부 삭제
SELECT A.EMPNO FROM EMP_COPY A, SALGRADE B
    WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL
    AND B.GRADE=2;
    
SELECT * FROM EMP_COPY WHERE EMPNO IN (SELECT A.EMPNO FROM EMP_COPY A, SALGRADE B
                                         WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL
                                            AND B.GRADE=2);

DELETE EMP_COPY WHERE EMPNO IN (SELECT A.EMPNO FROM EMP_COPY A, SALGRADE B
    WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL
    AND B.GRADE=2);

SELECT A.EMPNO FROM EMP_COPY A, SALGRADE B
    WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL
    AND B.GRADE=2;

--테이블 행 삭제 = 데이터 전체 삭제
DELETE EMP_COPY;
SELECT*FROM EMP_COPY;

--테이블 행 + 열 삭제 = 테이블 삭제
SELECT*FROM DEPT_COPY;
DROP TABLE DEPT_COPY;
SELECT*FROM DEPT_COPY; -- 확인 불가, 테이블 전체 삭제

CREATE TABLE DEPT_COPY
    AS SELECT*FROM DEPT;

SELECT*FROM DEPT_COPY;
INSERT INTO DEPT_COPY VALUES(50,'DA','SEOUL');
SELECT*FROM DEPT_COPY;
UPDATE DEPT_COPY
    SET LOC='SUWON'
    WHERE DEPTNO =50;
SELECT *FROM DEPT_COPY;
DELETE DEPT_COPY WHERE DNAME='ACCOUNTING';
SELECT*FROM DEPT_COPY;
ROLLBACK;
SELECT*FROM DEPT_COPY;

SELECT*FROM DEPT_COPY;
INSERT INTO DEPT_COPY VALUES(50,'DA','SEOUL');
SELECT*FROM DEPT_COPY;
UPDATE DEPT_COPY
    SET LOC='SUWON'
    WHERE DEPTNO =50;
SELECT *FROM DEPT_COPY;
DELETE DEPT_COPY WHERE DNAME='ACCOUNTING';
SELECT*FROM DEPT_COPY;
COMMIT;
SELECT*FROM DEPT_COPY;

--편집은 sqldeveloper에서, 붙여넣기는 sqlplus에서 ...,,,
--sqldeveloper, sqlplus 각자 실행
SELECT * FROM DEPT_COPY;
--현재 양쪽에 보여지는 결과는 동일함
--sqldeveloper에서 데이터 삭제
DELETE DEPT_COPY WHERE DEPTNO =50;
--sqlldeveloper, sqlplus 각자 실행
SELECT*FROM DEPT_COPY;
--sqldeveloper에서 최종 변경
COMMIT;
--sqlldeveloper, sqlplus 각자 실행
SELECT*FROM DEPT_COPY;


--sqlldeveloper, sqlplus 각자 실행
UPDATE DEPT_COPY
    SET DNAME = 'DA'
    WHERE DEPTNO =30;
--sqldeveloper에서 최종 변경
COMMIT;
SELECT*FROM DEPT_COPY;

--데이터 정의어 DDL : DATA DEFINITION LANGUAGE => 자동으로 COMMIT 된당
--열 이름과 자료형을 정의하면서 테이블 생성
DROP TABLE EMP_COPY;
CREATE TABLE EMP_COPY(
    EMPNO    NUMBER(4),
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(10),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2)
    );
SELECT*FROM EMP_COPY;

--2) 전체 행과 열을 복사하여 테이블 생성 = 열구조+데이터
SELECT*FROM DEPT_COPY;
DROP TABLE DEPT_COPY;
CREATE TABLE DEPT_COPY
    AS SELECT * FROM DEPT;

SELECT*FROM DEPT_COPY;

--3) 일부만 복사하여 테이블 생성
CREATE TABLE DEPT_COPY_30
    AS SELECT * FROM DEPT WHERE DEPTNO =30;

SELECT * FROM DEPT_COPY_30;

--4) 열을 복사하여 테이블 생성 = 열 구조 = 행이 없음
SELECT A.EMPNO, A.ENAME, A.HIREDATE, A.SAL, B.DEPTNO, B.DNAME
    FROM  EMP A, DEPT B
    WHERE A.DEPTNO = B.DEPTNO;


CREATE TABLE EMP_DEPT
    AS SELECT A.EMPNO, A.ENAME, A.HIREDATE, A.SAL, B.DEPTNO, B.DNAME
    FROM  EMP A, DEPT B
    WHERE 1=2;

SELECT*FROM EMP_DEPT;

--ALTER : 변경
--테이블 변경
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;

--1)열 추가
ALTER TABLE EMP_ALTER
    ADD PHONE VARCHAR2(15);

SELECT * FROM EMP_ALTER;

--2)열 이름 변경
ALTER TABLE EMP_ALTER
    RENAME COLUMN PHONE TO CP;
    
SELECT * FROM EMP_ALTER;

--3) 열의 데이터 타입 변경
DESC EMP_ALTER;
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--4) 열삭제
ALTER TABLE EMP_ALTER
    DROP COLUMN CP;

SELECT * FROM EMP_ALTER;

--테이블 이름 변경
RENAME EMP_ALTER TO EMP_ALTER_AFTER;
DESC EMP_ALTER;
DESC EMP_ALTER_AFTER;

--테이블 삭제 = 테이블 비우기
TRUNCATE TABLE EMP_ALTER_AFTER;S
SELECT* FROM EMP_ALTER_AFTER;

--테이블삭제
DROP TABLE EMP_ALTER_AFTER;
SELECT*FROM EMP_ALTER_AFTER;